<?php

namespace Modules\Kontak\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class KontakSeeder extends Seeder
{
    public function run()
    {
        DB::table('kontaks')->insert([
            [
                'nama' => 'Admin Dummy',
                'email' => 'admin@example.com',
                'subject' => 'Tes Kontak',
                'message' => 'Ini pesan kontak contoh generated by Apakek',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
